// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEP793RnIGfcc11PLty1vhrUit-bZXY_E',
    appId: '1:739941194529:web:02dcb3ba16da29c65c3c60',
    messagingSenderId: '739941194529',
    projectId: 'atelia-mandala',
    authDomain: 'atelia-mandala.firebaseapp.com',
    storageBucket: 'atelia-mandala.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjcT8Vq5LPTNmeaOeonN7ydURH7r-gL20',
    appId: '1:739941194529:android:181053e9bca143035c3c60',
    messagingSenderId: '739941194529',
    projectId: 'atelia-mandala',
    storageBucket: 'atelia-mandala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLZjTdxzuBwpSnUPxIGIcWZR6-lqDPfg',
    appId: '1:739941194529:ios:f36fda0dd86c91f25c3c60',
    messagingSenderId: '739941194529',
    projectId: 'atelia-mandala',
    storageBucket: 'atelia-mandala.appspot.com',
    iosBundleId: 'com.atelier.admin.atelierAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLZjTdxzuBwpSnUPxIGIcWZR6-lqDPfg',
    appId: '1:739941194529:ios:f36fda0dd86c91f25c3c60',
    messagingSenderId: '739941194529',
    projectId: 'atelia-mandala',
    storageBucket: 'atelia-mandala.appspot.com',
    iosBundleId: 'com.atelier.admin.atelierAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEP793RnIGfcc11PLty1vhrUit-bZXY_E',
    appId: '1:739941194529:web:affe8350e3467afc5c3c60',
    messagingSenderId: '739941194529',
    projectId: 'atelia-mandala',
    authDomain: 'atelia-mandala.firebaseapp.com',
    storageBucket: 'atelia-mandala.appspot.com',
  );
}
